# The configuration schema is defined by service.proto file
# https://github.com/googleapis/googleapis/blob/master/google/api/service.proto
type: google.api.Service
config_version: 3

#
# Name of the service configuration.
#
name: push.go.endpoint.endpoints.{PROJECT_ID}.cloud.goog

#
# API title to appear in the user interface (Google Cloud Console).
#
title: push-go-endpoint gRPC API
apis:
- name: push.FirebaseCloudMessagingEndpointService

#
# API usage restrictions.
#
usage:
  rules:
  # methods can not be called without an API Key.
  - selector: push.FirebaseCloudMessagingEndpointService.Set
    allow_unregistered_calls: false

  - selector: push.FirebaseCloudMessagingEndpointService.Delete
    allow_unregistered_calls: false

  - selector: push.FirebaseCloudMessagingEndpointService.Update
    allow_unregistered_calls: false

  - selector: push.FirebaseCloudMessagingEndpointService.Get
    allow_unregistered_calls: false
